### ISSUE TITLE
Possibility to move a value to a new position in the Y.Array

### ISSUE THREAD

**Issue by dennislaupman** [y-js/y-array#10]
Hello,

We have some problems with moving (ordering) big Y.Map sets to a new position in the Y.Array.

**How it works now:**
- delete old position
- create at new position

With big data sets this is a very heave performance task.

**Maybe its possible to "repoint" the maps to the new position. Something like:**
Array.reindex(old, new) 
Array.reindex(2, 3)

Grtz Dennis

**Comment by dmonad** [comment]
Hey Dennis,
I like the idea of a map that points to a new position. The data-structure behind y-array is actually a list, but it would still be possible to implement a map that "moves" the list-items to a different position. Here is the thing:
I need to access the re-ordering map for every item in the list. I am not sure if you would get any performance benefits. Furthermore, you need to create a map item instead of the list-item. So there is really no performance or memory benefit.

There is something you would get out of it: you can actually ensure that an element is moved only once. This would be great for shopping-lists where users can move elements to the top or bottom.
But I think there is a better algorithm for this use-case. Let me know if you want me to describe it.

But thanks for your feedback
